### ISSUE TITLE
Running the example - no result

### ISSUE THREAD

**Issue by alexbjorlig** [mindspank/serializeapp#4]
I tried running the provided example on a fresh install of Qlik Sense 3.1.  The connection seems to be established, but nothing is printed to the console. 

`qsocks.Connect().then(function(global) {
    global.openApp('Executive Dashboard.qvf')
        .then(function(app) {
            return serializeapp(app);
        })
        .then(function(data) {
            console.log(data) // --> A JSON Object describing the app.
        })
})`

**Comment by mindspank** [comment]
Gah, my bad. The example had non-working pseudo code. Fixed in commit https://github.com/mindspank/serializeapp/commit/d08310b73ad5b5a0406e8f3e6bdd61a7402998a0
